/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as BowlersIndexRouteImport } from './routes/bowlers.index'
import { Route as BowlersSlugRouteImport } from './routes/bowlers.$slug'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TeamsSlugRouteImport } from './routes/teams.$slug'
import { Route as AdminEntryIndexRouteImport } from './routes/admin.entry.index'
import { Route as AdminEntryMatchIdRouteImport } from './routes/admin.entry.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const BowlersIndexRoute = BowlersIndexRouteImport.update({
  id: '/bowlers/',
  path: '/bowlers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BowlersSlugRoute = BowlersSlugRouteImport.update({
  id: '/bowlers/$slug',
  path: '/bowlers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsSlugRoute = TeamsSlugRouteImport.update({
  id: '/teams/$slug',
  path: '/teams/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntryIndexRoute = AdminEntryIndexRouteImport.update({
  id: '/entry/',
  path: '/entry/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntryMatchIdRoute = AdminEntryMatchIdRouteImport.update({
  id: '/entry/$matchId',
  path: '/entry/$matchId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/results': typeof ResultsRoute
  '/schedule': typeof ScheduleRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/bowlers/$slug': typeof BowlersSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/bowlers/': typeof BowlersIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/admin/entry/$matchId': typeof AdminEntryMatchIdRoute
  '/admin/entry/': typeof AdminEntryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/results': typeof ResultsRoute
  '/schedule': typeof ScheduleRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/bowlers/$slug': typeof BowlersSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/bowlers': typeof BowlersIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/admin/entry/$matchId': typeof AdminEntryMatchIdRoute
  '/admin/entry': typeof AdminEntryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/results': typeof ResultsRoute
  '/schedule': typeof ScheduleRoute
  '/standings': typeof StandingsRoute
  '/stats': typeof StatsRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/bowlers/$slug': typeof BowlersSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/bowlers/': typeof BowlersIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/admin/entry/$matchId': typeof AdminEntryMatchIdRoute
  '/admin/entry/': typeof AdminEntryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/results'
    | '/schedule'
    | '/standings'
    | '/stats'
    | '/admin/schedule'
    | '/admin/teams'
    | '/bowlers/$slug'
    | '/match/$matchId'
    | '/teams/$slug'
    | '/admin/'
    | '/bowlers/'
    | '/teams/'
    | '/admin/entry/$matchId'
    | '/admin/entry/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/results'
    | '/schedule'
    | '/standings'
    | '/stats'
    | '/admin/schedule'
    | '/admin/teams'
    | '/bowlers/$slug'
    | '/match/$matchId'
    | '/teams/$slug'
    | '/admin'
    | '/bowlers'
    | '/teams'
    | '/admin/entry/$matchId'
    | '/admin/entry'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/results'
    | '/schedule'
    | '/standings'
    | '/stats'
    | '/admin/schedule'
    | '/admin/teams'
    | '/bowlers/$slug'
    | '/match/$matchId'
    | '/teams/$slug'
    | '/admin/'
    | '/bowlers/'
    | '/teams/'
    | '/admin/entry/$matchId'
    | '/admin/entry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ResultsRoute: typeof ResultsRoute
  ScheduleRoute: typeof ScheduleRoute
  StandingsRoute: typeof StandingsRoute
  StatsRoute: typeof StatsRoute
  BowlersSlugRoute: typeof BowlersSlugRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  TeamsSlugRoute: typeof TeamsSlugRoute
  BowlersIndexRoute: typeof BowlersIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bowlers/': {
      id: '/bowlers/'
      path: '/bowlers'
      fullPath: '/bowlers/'
      preLoaderRoute: typeof BowlersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bowlers/$slug': {
      id: '/bowlers/$slug'
      path: '/bowlers/$slug'
      fullPath: '/bowlers/$slug'
      preLoaderRoute: typeof BowlersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$slug': {
      id: '/teams/$slug'
      path: '/teams/$slug'
      fullPath: '/teams/$slug'
      preLoaderRoute: typeof TeamsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entry/': {
      id: '/admin/entry/'
      path: '/entry'
      fullPath: '/admin/entry/'
      preLoaderRoute: typeof AdminEntryIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entry/$matchId': {
      id: '/admin/entry/$matchId'
      path: '/entry/$matchId'
      fullPath: '/admin/entry/$matchId'
      preLoaderRoute: typeof AdminEntryMatchIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEntryMatchIdRoute: typeof AdminEntryMatchIdRoute
  AdminEntryIndexRoute: typeof AdminEntryIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminScheduleRoute: AdminScheduleRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEntryMatchIdRoute: AdminEntryMatchIdRoute,
  AdminEntryIndexRoute: AdminEntryIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ResultsRoute: ResultsRoute,
  ScheduleRoute: ScheduleRoute,
  StandingsRoute: StandingsRoute,
  StatsRoute: StatsRoute,
  BowlersSlugRoute: BowlersSlugRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  TeamsSlugRoute: TeamsSlugRoute,
  BowlersIndexRoute: BowlersIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
