/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LaneDataRouteImport } from './routes/lane-data'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as SinglesRouteImport } from './routes/singles'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminSinglesRouteImport } from './routes/admin.singles'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as BowlersIndexRouteImport } from './routes/bowlers.index'
import { Route as BowlersSlugRouteImport } from './routes/bowlers.$slug'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as StandingsIndexRouteImport } from './routes/standings.index'
import { Route as StatsIndexRouteImport } from './routes/stats.index'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as TeamsSlugRouteImport } from './routes/teams.$slug'
import { Route as AdminEntryIndexRouteImport } from './routes/admin.entry.index'
import { Route as AdminEntryMatchIdRouteImport } from './routes/admin.entry.$matchId'
import { Route as StandingsPrintCurrentThirdRouteImport } from './routes/standings.print.current-third'
import { Route as StandingsPrintFullRouteImport } from './routes/standings.print.full'
import { Route as StatsPrintBowlersRouteImport } from './routes/stats.print.bowlers'
import { Route as StatsPrintTeamsRouteImport } from './routes/stats.print.teams'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LaneDataRoute = LaneDataRouteImport.update({
  id: '/lane-data',
  path: '/lane-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const SinglesRoute = SinglesRouteImport.update({
  id: '/singles',
  path: '/singles',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSinglesRoute = AdminSinglesRouteImport.update({
  id: '/singles',
  path: '/singles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const BowlersIndexRoute = BowlersIndexRouteImport.update({
  id: '/bowlers/',
  path: '/bowlers/',
  getParentRoute: () => rootRouteImport,
} as any)
const BowlersSlugRoute = BowlersSlugRouteImport.update({
  id: '/bowlers/$slug',
  path: '/bowlers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsIndexRoute = StandingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StandingsRoute,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StatsRoute,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsSlugRoute = TeamsSlugRouteImport.update({
  id: '/teams/$slug',
  path: '/teams/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEntryIndexRoute = AdminEntryIndexRouteImport.update({
  id: '/entry/',
  path: '/entry/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEntryMatchIdRoute = AdminEntryMatchIdRouteImport.update({
  id: '/entry/$matchId',
  path: '/entry/$matchId',
  getParentRoute: () => AdminRoute,
} as any)
const StandingsPrintCurrentThirdRoute =
  StandingsPrintCurrentThirdRouteImport.update({
    id: '/print/current-third',
    path: '/print/current-third',
    getParentRoute: () => StandingsRoute,
  } as any)
const StandingsPrintFullRoute = StandingsPrintFullRouteImport.update({
  id: '/print/full',
  path: '/print/full',
  getParentRoute: () => StandingsRoute,
} as any)
const StatsPrintBowlersRoute = StatsPrintBowlersRouteImport.update({
  id: '/print/bowlers',
  path: '/print/bowlers',
  getParentRoute: () => StatsRoute,
} as any)
const StatsPrintTeamsRoute = StatsPrintTeamsRouteImport.update({
  id: '/print/teams',
  path: '/print/teams',
  getParentRoute: () => StatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/lane-data': typeof LaneDataRoute
  '/results': typeof ResultsRoute
  '/schedule': typeof ScheduleRoute
  '/singles': typeof SinglesRoute
  '/standings': typeof StandingsRouteWithChildren
  '/stats': typeof StatsRouteWithChildren
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/singles': typeof AdminSinglesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/bowlers/$slug': typeof BowlersSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/bowlers/': typeof BowlersIndexRoute
  '/standings/': typeof StandingsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/admin/entry/$matchId': typeof AdminEntryMatchIdRoute
  '/standings/print/current-third': typeof StandingsPrintCurrentThirdRoute
  '/standings/print/full': typeof StandingsPrintFullRoute
  '/stats/print/bowlers': typeof StatsPrintBowlersRoute
  '/stats/print/teams': typeof StatsPrintTeamsRoute
  '/admin/entry/': typeof AdminEntryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lane-data': typeof LaneDataRoute
  '/results': typeof ResultsRoute
  '/schedule': typeof ScheduleRoute
  '/singles': typeof SinglesRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/singles': typeof AdminSinglesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/bowlers/$slug': typeof BowlersSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/bowlers': typeof BowlersIndexRoute
  '/standings': typeof StandingsIndexRoute
  '/stats': typeof StatsIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/admin/entry/$matchId': typeof AdminEntryMatchIdRoute
  '/standings/print/current-third': typeof StandingsPrintCurrentThirdRoute
  '/standings/print/full': typeof StandingsPrintFullRoute
  '/stats/print/bowlers': typeof StatsPrintBowlersRoute
  '/stats/print/teams': typeof StatsPrintTeamsRoute
  '/admin/entry': typeof AdminEntryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/lane-data': typeof LaneDataRoute
  '/results': typeof ResultsRoute
  '/schedule': typeof ScheduleRoute
  '/singles': typeof SinglesRoute
  '/standings': typeof StandingsRouteWithChildren
  '/stats': typeof StatsRouteWithChildren
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/singles': typeof AdminSinglesRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/bowlers/$slug': typeof BowlersSlugRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/teams/$slug': typeof TeamsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/bowlers/': typeof BowlersIndexRoute
  '/standings/': typeof StandingsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/admin/entry/$matchId': typeof AdminEntryMatchIdRoute
  '/standings/print/current-third': typeof StandingsPrintCurrentThirdRoute
  '/standings/print/full': typeof StandingsPrintFullRoute
  '/stats/print/bowlers': typeof StatsPrintBowlersRoute
  '/stats/print/teams': typeof StatsPrintTeamsRoute
  '/admin/entry/': typeof AdminEntryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/lane-data'
    | '/results'
    | '/schedule'
    | '/singles'
    | '/standings'
    | '/stats'
    | '/admin/schedule'
    | '/admin/singles'
    | '/admin/teams'
    | '/bowlers/$slug'
    | '/match/$matchId'
    | '/teams/$slug'
    | '/admin/'
    | '/bowlers/'
    | '/standings/'
    | '/stats/'
    | '/teams/'
    | '/admin/entry/$matchId'
    | '/standings/print/current-third'
    | '/standings/print/full'
    | '/stats/print/bowlers'
    | '/stats/print/teams'
    | '/admin/entry/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lane-data'
    | '/results'
    | '/schedule'
    | '/singles'
    | '/admin/schedule'
    | '/admin/singles'
    | '/admin/teams'
    | '/bowlers/$slug'
    | '/match/$matchId'
    | '/teams/$slug'
    | '/admin'
    | '/bowlers'
    | '/standings'
    | '/stats'
    | '/teams'
    | '/admin/entry/$matchId'
    | '/standings/print/current-third'
    | '/standings/print/full'
    | '/stats/print/bowlers'
    | '/stats/print/teams'
    | '/admin/entry'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/lane-data'
    | '/results'
    | '/schedule'
    | '/singles'
    | '/standings'
    | '/stats'
    | '/admin/schedule'
    | '/admin/singles'
    | '/admin/teams'
    | '/bowlers/$slug'
    | '/match/$matchId'
    | '/teams/$slug'
    | '/admin/'
    | '/bowlers/'
    | '/standings/'
    | '/stats/'
    | '/teams/'
    | '/admin/entry/$matchId'
    | '/standings/print/current-third'
    | '/standings/print/full'
    | '/stats/print/bowlers'
    | '/stats/print/teams'
    | '/admin/entry/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LaneDataRoute: typeof LaneDataRoute
  ResultsRoute: typeof ResultsRoute
  ScheduleRoute: typeof ScheduleRoute
  SinglesRoute: typeof SinglesRoute
  StandingsRoute: typeof StandingsRouteWithChildren
  StatsRoute: typeof StatsRouteWithChildren
  BowlersSlugRoute: typeof BowlersSlugRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  TeamsSlugRoute: typeof TeamsSlugRoute
  BowlersIndexRoute: typeof BowlersIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lane-data': {
      id: '/lane-data'
      path: '/lane-data'
      fullPath: '/lane-data'
      preLoaderRoute: typeof LaneDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/singles': {
      id: '/singles'
      path: '/singles'
      fullPath: '/singles'
      preLoaderRoute: typeof SinglesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/singles': {
      id: '/admin/singles'
      path: '/singles'
      fullPath: '/admin/singles'
      preLoaderRoute: typeof AdminSinglesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/bowlers/': {
      id: '/bowlers/'
      path: '/bowlers'
      fullPath: '/bowlers/'
      preLoaderRoute: typeof BowlersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bowlers/$slug': {
      id: '/bowlers/$slug'
      path: '/bowlers/$slug'
      fullPath: '/bowlers/$slug'
      preLoaderRoute: typeof BowlersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings/': {
      id: '/standings/'
      path: '/'
      fullPath: '/standings/'
      preLoaderRoute: typeof StandingsIndexRouteImport
      parentRoute: typeof StandingsRoute
    }
    '/stats/': {
      id: '/stats/'
      path: '/'
      fullPath: '/stats/'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof StatsRoute
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$slug': {
      id: '/teams/$slug'
      path: '/teams/$slug'
      fullPath: '/teams/$slug'
      preLoaderRoute: typeof TeamsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/entry/': {
      id: '/admin/entry/'
      path: '/entry'
      fullPath: '/admin/entry/'
      preLoaderRoute: typeof AdminEntryIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/entry/$matchId': {
      id: '/admin/entry/$matchId'
      path: '/entry/$matchId'
      fullPath: '/admin/entry/$matchId'
      preLoaderRoute: typeof AdminEntryMatchIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/standings/print/current-third': {
      id: '/standings/print/current-third'
      path: '/print/current-third'
      fullPath: '/standings/print/current-third'
      preLoaderRoute: typeof StandingsPrintCurrentThirdRouteImport
      parentRoute: typeof StandingsRoute
    }
    '/standings/print/full': {
      id: '/standings/print/full'
      path: '/print/full'
      fullPath: '/standings/print/full'
      preLoaderRoute: typeof StandingsPrintFullRouteImport
      parentRoute: typeof StandingsRoute
    }
    '/stats/print/bowlers': {
      id: '/stats/print/bowlers'
      path: '/print/bowlers'
      fullPath: '/stats/print/bowlers'
      preLoaderRoute: typeof StatsPrintBowlersRouteImport
      parentRoute: typeof StatsRoute
    }
    '/stats/print/teams': {
      id: '/stats/print/teams'
      path: '/print/teams'
      fullPath: '/stats/print/teams'
      preLoaderRoute: typeof StatsPrintTeamsRouteImport
      parentRoute: typeof StatsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminSinglesRoute: typeof AdminSinglesRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEntryMatchIdRoute: typeof AdminEntryMatchIdRoute
  AdminEntryIndexRoute: typeof AdminEntryIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminScheduleRoute: AdminScheduleRoute,
  AdminSinglesRoute: AdminSinglesRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEntryMatchIdRoute: AdminEntryMatchIdRoute,
  AdminEntryIndexRoute: AdminEntryIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StandingsRouteChildren {
  StandingsIndexRoute: typeof StandingsIndexRoute
  StandingsPrintCurrentThirdRoute: typeof StandingsPrintCurrentThirdRoute
  StandingsPrintFullRoute: typeof StandingsPrintFullRoute
}

const StandingsRouteChildren: StandingsRouteChildren = {
  StandingsIndexRoute: StandingsIndexRoute,
  StandingsPrintCurrentThirdRoute: StandingsPrintCurrentThirdRoute,
  StandingsPrintFullRoute: StandingsPrintFullRoute,
}

const StandingsRouteWithChildren = StandingsRoute._addFileChildren(
  StandingsRouteChildren,
)

interface StatsRouteChildren {
  StatsIndexRoute: typeof StatsIndexRoute
  StatsPrintBowlersRoute: typeof StatsPrintBowlersRoute
  StatsPrintTeamsRoute: typeof StatsPrintTeamsRoute
}

const StatsRouteChildren: StatsRouteChildren = {
  StatsIndexRoute: StatsIndexRoute,
  StatsPrintBowlersRoute: StatsPrintBowlersRoute,
  StatsPrintTeamsRoute: StatsPrintTeamsRoute,
}

const StatsRouteWithChildren = StatsRoute._addFileChildren(StatsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LaneDataRoute: LaneDataRoute,
  ResultsRoute: ResultsRoute,
  ScheduleRoute: ScheduleRoute,
  SinglesRoute: SinglesRoute,
  StandingsRoute: StandingsRouteWithChildren,
  StatsRoute: StatsRouteWithChildren,
  BowlersSlugRoute: BowlersSlugRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  TeamsSlugRoute: TeamsSlugRoute,
  BowlersIndexRoute: BowlersIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
